apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/FazalM/EKS-Game.git   # my repo
    targetRevision: staging                           # branch
    path: manifest                                 # my folder in repo where k8s yaml lives
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
