name: Infra + Docker Pipeline

on:
  push:
    branches: [ "staging", "main" ]
    paths: ['CD-pipeline/**']

permissions:
  id-token: write     # required for OIDC to work
  contents: read      # required for checkout if you add it later

jobs:
  bootstrap-argocd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 🔹 Debug: print the OIDC token claims
      - name: Print OIDC token claims
        run: |
          OIDC_TOKEN=$(curl -sSL -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com" | jq -r .value)
          echo "Decoded claims:"
          echo $OIDC_TOKEN | cut -d. -f2 | base64 -d | jq

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::662348578823:role/GitHubActionsRole

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name my-cluster

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Add Argo Helm repo
        run: |
          helm repo add argo https://argoproj.github.io/argo-helm
          helm repo update

      - name: Install ArgoCD
        run: |
          kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -
          helm upgrade --install argocd argo/argo-cd \
            --namespace argocd \
            --create-namespace \
            --version 7.7.3

      - name: Run ArgoCD as app
        run: |
          kubectl apply -f argocd-app.yaml -n argocd

      # Argo Rollouts
      - name: Install Argo Rollouts
        run: |
          kubectl create namespace argo-rollouts --dry-run=client -o yaml | kubectl apply -f -
          helm upgrade --install argo-rollouts argo/argo-rollouts \
            --namespace argo-rollouts \
            --create-namespace



